name: bip32_ed25519
description: The Dart implementation of the BIP32-Ed25519 the deterministic key generation solution for the Ed25519 curve.
version: 0.0.1-nullsafety.0
homepage: https://github.com/ilap/bip32-ed25519-dart
publish_to: none
environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  #pinenacl: ^0.2.0-nullsafety
  pinenacl:
    path: ../pinenacl-dart

dev_dependencies:
  bip39: 
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
  benchmark_harness: ^2.0.0-nullsafety
